services:

  cassandra-server:
    image: cassandra:latest
    platform: linux/x86_64
    restart: unless-stopped
    container_name: cassandra-server
    ports:
      - "7001:7000"
      - "9042:9042"
    volumes:
      - cassandra-server_data:/var/lib/cassandra:rw
      - cassandra-server_conf:/etc/cassandra:rw
    environment:
      - CASSANDRA_START_RPC=true       # default
      - CASSANDRA_RPC_ADDRESS=0.0.0.0  # default
      - CASSANDRA_LISTEN_ADDRESS=auto  # default, use IP addr of container # = CASSANDRA_BROADCAST_ADDRESS
      - CASSANDRA_CLUSTER_NAME=cluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=256M
    networks:
      - cassandra-network
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 2m
      start_period: 2m
      timeout: 10s
      retries: 3

volumes:
  cassandra-server_data:
    name: cassandra-server_data
  cassandra-server_conf:
    name: cassandra-server_conf
networks:
  cassandra-network:
    name: cassandra-network
    driver: bridge