version: "3.9"  # optional since v1.27.0
services:

## docker-registry-server
  docker-registry-server:
    image: registry:latest
    platform: linux/x86_64
    restart: always
    container_name: docker-registry-server
    ports:
      - "5000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
    volumes:
      - docker-registry-server_data:/data
      - docker-registry-server_registry:/var/lib/registry
      - ./docker-registry:/auth
    networks:
      - docker-registry-network

volumes:
  docker-registry-server_data:
    name: docker-registry-server_data
  docker-registry-server_registry:
    name: docker-registry-server_registry

networks:
  docker-registry-network:
    name: docker-registry-network
    driver: bridge