services:
  kafka-zookeeper:
    image: confluentinc/cp-zookeeper:latest
    platform: linux/x86_64
    restart: unless-stopped
    container_name: kafka-zookeeper
    ports:
      - "2181:2181"
    volumes:
      - kafka-zookeeper_secrets:/etc/zookeeper/secrets
      - kafka-zookeeper_data:/var/lib/zookeeper/data
      - kafka-zookeeper_log:/var/lib/zookeeper/log
    environment:
      ZOOKEEPER_CLIENT_PORT: '2181'
      ZOOKEEPER_SERVER_ID: '1'
      ZOOKEEPER_SERVERS: 'kafka-zookeeper:2888:3888'
      ZOOKEEPER_TICK_TIME: '2000'
    networks:
      - kafka-network
  kafka-broker:
    image: confluentinc/cp-kafka:latest
    platform: linux/x86_64
    restart: unless-stopped
    container_name: kafka-broker
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9999:9999"
    depends_on:
      - kafka-zookeeper
    volumes:
      - kafka-broker_secrets:/etc/kafka/secrets
      - kafka-broker_data:/var/lib/kafka/data
    environment:
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka-broker:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_ZOOKEEPER_CONNECT: 'kafka-zookeeper:2181'
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: 'kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: '1'
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: '1'
      KAFKA_JMX_PORT: '9999'
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_AUTHORIZER_CLASS_NAME: 'kafka.security.authorizer.AclAuthorizer'
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: 'true'
    networks:
      - kafka-network

volumes:
  kafka-zookeeper_secrets:
    name: kafka-zookeeper_secrets
  kafka-zookeeper_data:
    name: kafka-zookeeper_data
  kafka-zookeeper_log:
    name: kafka-zookeeper_log
  kafka-broker_secrets:
    name: kafka-broker_secrets
  kafka-broker_data:
    name: kafka-broker_data

networks:
  kafka-network:
    name: kafka-network
    driver: bridge

