version: "3.9"  # optional since v1.27.0
services:

  mongo-server:
    image: mongo:latest
    platform: linux/x86_64
    restart: unless-stopped
    container_name: mongo-server
    ports:
      - "27017:27017"
    volumes:
      - mongo-server_data:/data/db
    networks:
      - mongo-network

volumes:
  mongo-server_data:
    name: mongo-server_data

networks:
  mongo-network:
    name: mongo-network
    driver: bridge
