services:

  mongo-server:
    image: mongo:latest
    platform: linux/x86_64
    restart: unless-stopped
    container_name: mongo-server
    ports:
      - "27017:27017"
    volumes:
      - mongo-server_data:/data/db
      - mongo-server_configdb:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'raven-dev'
      MONGO_INITDB_ROOT_PASSWORD: 'Raven123qweasd*+'
    networks:
      - mongo-network

volumes:
  mongo-server_data:
    name: mongo-server_data
  mongo-server_configdb:
    name: mongo-server_configdb

networks:
  mongo-network:
    name: mongo-network
    driver: bridge
