services:

## nats
  nats-server:
    image: nats:2.10.20-alpine3.20
    platform: linux/x86_64
    restart: unless-stopped
    container_name: nats-server
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    networks:
      - nats-network

networks:
  nats-network:
    name: nats-network
    driver: bridge
