services:

## nats
  nats-server:
    image: nats:latest
    platform: linux/x86_64
    restart: unless-stopped
    container_name: nats-server
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    networks:
      - nats-network

networks:
  nats-network:
    name: nats-network
    driver: bridge
